version = 0.1

[default.deploy.parameters]
stack_name = "wedding-media"
resolve_s3 = true
s3_prefix = "wedding-media"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SiteOrigin=\"*\" SingleShotLimitMB=\"8\" PartSizeMB=\"16\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
